require('angular');
require('angular-cookies');
require('angular-ui-router');
require('angular-resource');
require('./config/config');
require('./controllers/home-controllers');
require('./controllers/forecast-controllers');
require('./services/weather-services');
require('./directives/directives');
